### ISSUE TITLE
must use "$lexers" in .inf

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_complete_html_text#1]
```
lexers=regex:HTML.*
homepage=https://github.com/halfbrained/cuda_complete_html_text
api=1.0.318

[item1]
section=events
events=on_complete+
```

[item1] must refer to 'lexers': like
```
lexers=$lexers
```
IIRC...

**Comment by halfbrained** [comment]
You are right. Additionally, regex declaration needs to be in the same section, this works:
``` ini
[item1]
section=events
lexers=regex:HTML.*
lexers=$lexers
events=on_complete+
```

**Comment by Alexey-T** [comment]
no!! the same key in the same section - is invalid INI. so you declare $myvar with any value, and then in [item1] you refer to it

lexers=$myvar

**Comment by halfbrained** [comment]
Ok, final attempt :)
``` ini
[item1]
section=events
lexers=regex:HTML.*
events=on_complete+
```
This actually triggers in HTML and HTML Diafan, but not Assembly -- so, solved?

**Comment by Alexey-T** [comment]
solved.
