### ISSUE TITLE
Words with 2 chars do not appear

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_complete_html_text#10]
![Peek 19-08-2021 19-16](https://user-images.githubusercontent.com/25956396/130151626-e7286ce7-7493-4242-860b-ccffa4ef6517.gif)

**Comment by Alexey-T** [comment]
Elton, plugin has the config file. It has the needed option min_len.

**Comment by eltonfabricio10** [comment]
Sorry! I forgot to restart Cud...
