### ISSUE TITLE
blocked CSS autocompletion

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_complete_html_text#11]
![Screenshot_20210912_225031](https://user-images.githubusercontent.com/25956396/133012703-7098aa11-b903-4145-a77d-14280f520f2d.jpg)

Between the "<style>...</style>" tags should show the CSS autocompletion

**Comment by Alexey-T** [comment]
working OK here. maybe the lexer of the whole document is incorrect, not html?

**Comment by Alexey-T** [comment]
See the 'html text' on screenshot, so it's caused by cuda_complete_html_text plugin. @halfbrained are you sure your plugin works OK in this context? please test?

**Comment by Alexey-T** [comment]
@halfbrained I dont see where your plugin calls PROP_LEXER_CARET, so it thinks that we are inside HTML context, while we are in CSS!

**Comment by Alexey-T** [comment]
Fix, `py/cuda_complete_html_text/__init__.py`
```
    def on_complete(self, ed_self):
        carets = ed_self.get_carets()
        if len(carets)!=1: return   # no multicaret
        x0, y0, x1, y1 = carets[0]
        if y1>=0: return    # don't allow selection

        # don't work inside CSS/PHP blocks
        lex = ed_self.get_prop(PROP_LEXER_CARET)
        if not 'HTML' in lex: return

        if not validate_caret_pos(ed_self, x0, y0): return   # check if caret in tag text  
```
@halfbrained

**Comment by eltonfabricio10** [comment]
Solved with this fix, thanks
