### ISSUE TITLE
feature: complete any text on id prop

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_complete_html_text#13]
```E.g. <div id="|">Cud</div>```

**Comment by Alexey-T** [comment]
HTML Class Complete plugin?

https://github.com/CudaText-addons/cuda_html_class_complete/tree/master/readme

**Comment by Alexey-T** [comment]
plugin?

title=HTML Completion
desc=Handles auto-completion (Ctrl+Space) in HTML/PHP files. 1) Auto-completion with file names, when caret is inside IMG tag. 2) Auto-completion with CSS class/id names, when caret is inside 'class=""' or 'id=""'.

**Comment by eltonfabricio10** [comment]
OK
