### ISSUE TITLE
don't work, 2

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_complete_html_text#4]
[new.zip](https://github.com/halfbrained/cuda_complete_html_text/files/7009027/new.zip)

- it don't work for line 19:
```
<!-- Glo|ssary Toolbar -->
```

- it don't work for line 25
```
yyy|yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```

**Comment by halfbrained** [comment]
Seems alright now?

**Comment by Alexey-T** [comment]
yes
